from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml

from prompt_builder import PromptBuilder
from speech_to_image import PromptEnhancer
from utils import slugify


def _to_rel(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except Exception:
        return str(path)


def _collect_for_view(system_dir: Path, product_id: str, target_view: str) -> list[Path]:
    product_dir = system_dir / product_id
    if not product_dir.exists():
        return []

    view_slug = slugify(target_view)
    preferred = sorted(product_dir.glob(f"{view_slug}_*.png"))
    if preferred:
        return preferred

    return sorted(product_dir.glob("*.png"))


def _make_markdown(
    rows: list[dict],
    code_prompt_catalog: dict,
    config_negative_prompt: str,
    out_file: Path,
    workspace_root: Path,
) -> str:
    lines: list[str] = []
    lines.append("# All Prompts and Outputs")
    lines.append("")
    lines.append(f"Generated by: {out_file.name}")
    lines.append("")

    lines.append("## 1) Prompts Defined in Code")
    lines.append("")
    lines.append("### Structured Prompt Template (from prompt_builder.py)")
    lines.append("")
    lines.append(code_prompt_catalog["structured_prompt_template"])
    lines.append("")

    lines.append("### Global Negative Prompt (from config)")
    lines.append("")
    lines.append(config_negative_prompt)
    lines.append("")

    lines.append("### Speech→Image Prompt Components (from speech_to_image.py)")
    lines.append("")
    lines.append("- ECOMMERCE_SUFFIX:")
    lines.append(code_prompt_catalog["speech_to_image_suffix"])
    lines.append("")
    lines.append("- NEGATIVE_PROMPT:")
    lines.append(code_prompt_catalog["speech_to_image_negative"])
    lines.append("")

    lines.append("## 2) Per-Row Prompt + Output Mapping")
    lines.append("")
    lines.append("| product_id | target_view | baseline_prompt | structured_prompt | negative_prompt | baseline_outputs | structured_outputs |")
    lines.append("|---|---|---|---|---|---|---|")

    for row in rows:
        b_out = "<br>".join(row["baseline_outputs"]) if row["baseline_outputs"] else "(none)"
        s_out = "<br>".join(row["structured_outputs"]) if row["structured_outputs"] else "(none)"

        def esc(text: str) -> str:
            return (
                str(text)
                .replace("|", "\\|")
                .replace("\n", " ")
                .strip()
            )

        lines.append(
            "| "
            + " | ".join(
                [
                    esc(row["product_id"]),
                    esc(row["target_view"]),
                    esc(row["baseline_prompt"]),
                    esc(row["structured_prompt"]),
                    esc(row["negative_prompt"]),
                    esc(b_out),
                    esc(s_out),
                ]
            )
            + " |"
        )

    lines.append("")
    lines.append("## 3) Output Inventory")
    lines.append("")

    baseline_count = sum(len(r["baseline_outputs"]) for r in rows)
    structured_count = sum(len(r["structured_outputs"]) for r in rows)
    lines.append(f"- Baseline output files found: {baseline_count}")
    lines.append(f"- Structured output files found: {structured_count}")
    lines.append(f"- Workspace root: {_to_rel(workspace_root, workspace_root)}")

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Export all prompts + outputs into one markdown file.")
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--metadata", default="data/sample_products.csv")
    parser.add_argument("--baseline_dir", default="outputs/baseline")
    parser.add_argument("--structured_dir", default="outputs/structured")
    parser.add_argument("--output_file", default="results/all_prompts_and_outputs.md")
    args = parser.parse_args()

    workspace_root = Path(__file__).resolve().parents[1]

    config_path = (workspace_root / args.config).resolve()
    metadata_path = (workspace_root / args.metadata).resolve()
    baseline_dir = (workspace_root / args.baseline_dir).resolve()
    structured_dir = (workspace_root / args.structured_dir).resolve()
    output_file = (workspace_root / args.output_file).resolve()

    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    prompt_builder = PromptBuilder(config)
    df = pd.read_csv(metadata_path)

    exported_rows: list[dict] = []
    for _, pd_row in df.iterrows():
        row = pd_row.to_dict()
        built = prompt_builder.build(row)

        baseline_outputs = [
            _to_rel(p, workspace_root)
            for p in _collect_for_view(baseline_dir, str(row["product_id"]), str(row["target_view"]))
        ]
        structured_outputs = [
            _to_rel(p, workspace_root)
            for p in _collect_for_view(structured_dir, str(row["product_id"]), str(row["target_view"]))
        ]

        exported_rows.append(
            {
                "product_id": str(row["product_id"]),
                "target_view": str(row["target_view"]),
                "baseline_prompt": built.baseline_prompt,
                "structured_prompt": built.structured_prompt,
                "negative_prompt": built.negative_prompt,
                "baseline_outputs": baseline_outputs,
                "structured_outputs": structured_outputs,
            }
        )

    prompt_catalog = {
        "structured_prompt_template": (
            "Commercial e-commerce product photo of {title}, {color}, made of {material}, "
            "{style} style. Key attributes: {attributes}. View: {target_view}. "
            "Scene: {environment}. {lighting}. {lens}. {composition}. "
            "Single product only, photorealistic, crisp edges, catalog-ready."
        ),
        "speech_to_image_suffix": PromptEnhancer.ECOMMERCE_SUFFIX,
        "speech_to_image_negative": PromptEnhancer.NEGATIVE_PROMPT,
    }

    markdown = _make_markdown(
        rows=exported_rows,
        code_prompt_catalog=prompt_catalog,
        config_negative_prompt=config.get("control", {}).get("negative_prompt", ""),
        out_file=output_file,
        workspace_root=workspace_root,
    )

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(markdown, encoding="utf-8")
    print(f"Saved prompts+outputs to {output_file}")


if __name__ == "__main__":
    main()
